# Generated by Django 4.2.15 on 2024-09-10 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_alter_article_abstract_alter_article_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(message='As palavras-chave devem ser frases separadas por ponto e espaço (ex: "Frase 1. Frase 2.").', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\s]+(\\.\\s*[A-Za-zÀ-ÖØ-öø-ÿ\\s]+)*\\.$')]),
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=400)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_project.article')),
            ],
        ),
    ]
