# Generated by Django 2.2.12 on 2024-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('date', models.PositiveIntegerField()),
                ('journal', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
