# Generated by Django 4.2.15 on 2024-11-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0011_articleauditlog_remove_auditlog_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Acesso'), ('DELETION', 'Exclusão de Dados')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='Não especificado', null=True),
        ),
    ]
