# Generated by Django 4.2.15 on 2024-11-20 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0012_alter_auditlog_action_alter_auditlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(upload_to='articles/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(10485760)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='articleauditlog',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='Ação realizada no sistema.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
