# Generated by Django 4.2.15 on 2024-11-20 01:28

import app_project.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0013_alter_article_pdf_file_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(upload_to='articles/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app_project.models.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Acesso'), ('DELETION', 'Exclusão de Dados'), ('OTHER', 'Outro')], max_length=100),
        ),
    ]
